server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/



spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: micro
  application:
    name: RATING-SERVICE




